"""Prompt bodies for slash commands that inject hidden system-reminder turns."""

import os

import micro_cc
from micro_cc.models.registry import MODEL_OPTIONS

# Absolute base for file pointers — model would timeout searching if left relative.
_PKG_DIR = os.path.dirname(os.path.abspath(micro_cc.__file__))

SETUP = (
    "The user ran /setup. You have bash_ available and three config "
    "files at ~/.micro-cc/ you can inspect and edit directly:\n"
    "  - settings.json — {model, dangerous: [tool names gated behind "
    "approval], tokens_budget}\n"
    "  - statusline.sh — controls the status bar shown under the "
    "input. It may not exist: then the builtin default runs from "
    "~/.micro-cc/cache/statusline.default.sh (harness-owned, rewritten each "
    "boot, never edit it). To customize, copy that to ~/.micro-cc/statusline.sh "
    "(chmod +x) and edit the copy. It's self-documenting, read its header comments before "
    "changing it - you can add new things like for example len(memories) "
    "styling it - keep same minimal style as current statusline.sh\n"
    "  - theme.json — {name, colors: {<token>: \"#rrggbb\", ...}} — every "
    "color in the TUI: bg, fg, accent, ok/error/warn/info, code_bg, "
    "banner_colors (list — the splash picks one at random per launch), "
    "and more. \"name\" is just a label. Edit a hex to retheme anything; "
    "the user can also switch whole presets live with /theme (white / "
    "pitch), which rewrites this file. Keep every token key present.\n"
    "Read all of them with bash_, explain to the user in plain terms what's "
    "currently configured and what they can change, then make any "
    "edits they ask for.\n"
    "\n"
    "ALSO tell the user the single most important thing about this "
    "harness, because it is unusual and it is the point: **you can change "
    "the harness itself, and it comes back changed.** micro·cc is not a "
    "compiled binary — it is plain, readable .py files, and the process "
    "runs them from wherever it is installed (a dev checkout, or a "
    "pip/pipx/brew/uv install — the poll watches the package dir either "
    "way). The running process is executing the code it imported at "
    "startup, so editing a tool, the agent loop, the TUI, or the system "
    "prompt assembly on disk has no effect until the process restarts and "
    "re-imports. That restart is wired in, so self-modification actually "
    "works:\n"
    "  - Edit any file under the package dir (e.g. this file's own "
    f"directory, {_PKG_DIR} — tools/, claude_loop_.py, tui_native/, "
    "utils/) with write_/edit_/bash_. A background poll notices the change "
    "and flashes a hint, but nothing restarts by itself: once the user "
    "allows it, YOU call reload_harness_ (load it with search_tools "
    "first) and the app relaunches at the end of that turn (an in-flight "
    "tool call or a live subagent is left to finish first). The "
    "conversation is stored on disk, so it keeps its place across the "
    "restart.\n"
    "  - The user can also force it with /reload.\n"
    "  - Because an edit can break the tree so the app won't start, the "
    "launch is guarded: if micro·cc fails to boot, a supervisor reinstalls "
    "the published wheel over the broken tree and retries (bounded), so a "
    "bad self-edit is recoverable rather than fatal. Note that reinstall "
    "replaces any local edits with the released version, and a plain "
    "/update does the same — worth saying, so nobody is surprised their "
    "change was overwritten by an upgrade.\n"
    "So if the user asks for a behavior change — 'make the status bar show "
    "X', 'add a tool that does Y', 'change how you plan', 'wake me in 20 "
    "minutes' (monitor_ has a schedule action) — you can implement it in "
    "the source and it will take effect. Say so plainly and concretely. "
    "Prefer a mod over a source edit: anything on screen beyond the status "
    "bar text, a slash command or a key binding goes in "
    "~/.micro-cc/mods/<name>/mod.py (read the customizing-micro-cc skill "
    "first). Mods survive /update; source edits don't. "
    "Only touch the harness's own source when the user actually asks for a "
    "behavior change; for their project's files, that's just normal work.\n"
)

SKILL = (
    "The user ran /new-skill to create a new skill. Skills load from "
    "~/.micro-cc/skills/<name>/SKILL.md (global, every project) or "
    "{project_dir}/skills/<name>/SKILL.md (this project only), each a "
    "SKILL.md with YAML frontmatter (name, description) plus the "
    "instructions the skill teaches. Interview the user in plain "
    "conversation: what should the skill do, when should it trigger, "
    "and does it belong at the global or project tier. Then write the "
    "SKILL.md file yourself with bash_/write_ and confirm what you "
    "created and where.\n"
)

MCP = (
    "The user ran /new-mcp to register a new MCP server. MCPs load "
    "from ~/.micro-cc/mcps/<name>/mcp.json (global, every project) or "
    "{project_dir}/mcps/<name>/mcp.json (this project only), each a "
    'mcp.json shaped {"server": {"type": "url", "url": "https://...", '
    '"name": "myserver"}, "search_text": "what this mcp is for — this '
    'one line is what the model sees under search_tools(action=\"discover\") '
    'when choosing whether to load it"}. Interview the user: what does the MCP server '
    "do, what's its URL/connection details, and does it belong at the "
    "global or project tier. Then write the mcp.json file yourself "
    "with bash_/write_ and confirm what you created and where.\n"
)

SKILLS_INFO = (
    "The user ran /skills to see what skills they have. Call the "
    "list_skills tool — it is already wired into every turn for exactly "
    "this, and returns the real, merged (built-in + global + "
    "project-local) name + description for every skill currently "
    "available. Do NOT use bash_ to go poking at the skills/ directories "
    "yourself — list_skills already did that. Report what it returns "
    "back to the user plainly. Skills load from three tiers, merged "
    "(later overrides earlier on a name clash): built-in "
    "({this package}/skills/<name>/SKILL.md), global "
    "(~/.micro-cc/skills/<name>/SKILL.md, applies to every project), and "
    "project-local ({project_dir}/skills/<name>/SKILL.md, this project "
    "only) — mention that structure so the user knows where things live, "
    "but get the actual list from the tool, not from bash_. Then explain "
    "how to add more: /new-skill creates one, and they choose global "
    "(~/.micro-cc/skills/) to have it everywhere or project-local "
    "({project_dir}/skills/) to scope it to just this project — or they "
    "can write a SKILL.md by hand in either location.\n"
)

MCP_INFO = (
    "The user ran /mcp to see what MCP servers they have. Call the "
    "list_mcps tool — it is already wired into every turn for exactly "
    "this, and returns the real, merged (built-in + global + "
    "project-local) name + url + what-it's-for for every MCP server "
    "currently available. Do NOT use bash_ to go poking at the mcps/ "
    "directories yourself, and don't use search_tools for this either — "
    "list_mcps returns the url and a fuller description for each server, "
    "where search_tools(action=\"discover\") truncates descriptions to "
    "keep its listing cheap. list_mcps already did the real "
    "listing. Report what it returns back to the user plainly. MCPs load "
    "from three tiers, merged (later overrides earlier on a name clash): "
    f"built-in (MCP_CATALOG in {_PKG_DIR}/tools/search_tool_.py), global "
    "(~/.micro-cc/mcps/<name>/mcp.json, applies to every project), and "
    "project-local ({project_dir}/mcps/<name>/mcp.json, this project "
    "only) — mention that structure so the user knows where things live, "
    "but get the actual list from the tool. Then explain how to add "
    "more: /new-mcp registers one, and they choose global "
    "(~/.micro-cc/mcps/) to have it everywhere or project-local "
    "({project_dir}/mcps/) to scope it to just this project — or they "
    "can write an mcp.json by hand in either location.\n"
)

HEADLESS = (
    "The user ran /headless to learn about single-prompt headless (no-UI) "
    "runs. These use the `microcc-headless <project_dir> \"<prompt>\"` CLI "
    f"(see {_PKG_DIR}/start_headless_.py) — the microcc equivalent of "
    "`claude -p`. It takes exactly one prompt (as an argument, or piped "
    "via stdin) and runs it once against project_dir's own conversation "
    "history — no manifest file, no task tree, nothing to write to disk "
    "first. It's meant to be invoked ad hoc or from cron whenever, not "
    "scheduled as a batch (for a batch of named tasks each in their own "
    "isolated subfolder, that's /batch instead).\n"
    "It runs with dangerous_tools=set() — fully autonomous, no approval "
    "gate, so scope prompts you suggest safely. The prompt automatically "
    "gets a status-marker instruction appended (the model must end its "
    "reply with 'STATUS: DONE — ...', 'STATUS: NEEDS_INPUT — ...', or "
    "'STATUS: FAILED — ...') so the outcome prints with a ✓/✗/? symbol "
    "instead of just dumping raw text — you don't need to add this "
    "yourself. If the model tries to ask the user a clarifying question "
    "mid-run, that gets auto-cancelled (nobody's there to answer) and the "
    "model is told to fold it into STATUS: NEEDS_INPUT instead of "
    "hanging.\n"
    "project_dir determines the conversation scope exactly like the "
    "interactive TUI does (~/.micro-cc/projects/{name}_{hash}/) — point "
    "repeated cron runs at the same project_dir to keep continuing the "
    "same history, or a fresh one for a stateless one-off.\n"
    "If the model tries to ask a clarifying question mid-run, it does NOT "
    "get auto-answered — the run stops immediately with STATUS: PAUSED and "
    "the question preserved, instead of the model guessing or fabricating "
    "an answer. Whoever's watching relaunches the same project_dir with "
    "the answer once they have it (`microcc-headless <same project_dir> "
    "\"<answer>\"`), which continues the same history — /graph automates "
    "the watching-and-relaunching part if you don't want to do that by "
    f"hand (mechanism: {_PKG_DIR}/start_live_.py's _poll_subagents_tick/"
    "_wake_for_subagent).\n"
    "It can also message_session_ another project_dir directly (a live TUI, "
    "or another headless run whether it's running right now or not — "
    "durable inbox fallback either way; mechanism: "
    f"{_PKG_DIR}/tools/message_session_.py).\n"
    "When a micro-cc session spawns it through bash_ (a /graph subagent), "
    "it doesn't block: it registers, detaches, and returns STARTED (with "
    "the pid) or REFUSED (e.g. the /subagents concurrency cap) at once; "
    "--foreground restores blocking. From cron or a plain terminal it "
    "always blocks and exits with the run's real status.\n"
    "Flags: -f/--file (repeatable, points the prompt at specific files), "
    "--model, --max-loops (caps tool-call rounds before self-stopping with "
    "STATUS: PAUSED instead of running unattended forever — relaunch the "
    "same project_dir to continue; unlimited if omitted), --output-format "
    "text|json (json wraps the result as {status, summary, body, "
    "project_dir} for scripting), --verbose (streams tool calls/results to "
    "stderr — useful in cron logs).\n"
    "Explain this to the user in plain terms and, if they describe a "
    "specific job they want to run on a schedule, give them the exact "
    "`microcc-headless` command line and a one-line crontab example — "
    "don't run it for them, it's meant to run unattended/out-of-band.\n"
)

DOCTOR = (
    "The user ran /doctor because /update failed, or they suspect their "
    "install is fragile. Your job: diagnose which interpreter this install "
    "actually runs on and whether that interpreter can self-update, then "
    "hand the user exact shell commands to fix it — never run the fix "
    "yourself. You have bash_ available.\n"
    "Ground truth for the interpreter: `head -1 \"$(command -v microcc)\"` "
    "— the entry-point script's shebang IS the exact python self-update "
    f"drives ({_PKG_DIR}/screens/self_update_.py's run_update calls "
    "`sys.executable -m pip install --upgrade --force-reinstall micro-cc`, "
    "and sys.executable resolves to that same shebang path). Call that "
    "path $PY for the checks below.\n"
    "Classify $PY by its path and check the failure modes that matter:\n"
    "  - contains /pipx/venvs/ → pipx-managed. Fix is `pipx uninstall "
    "micro-cc && pipx install micro-cc`, never raw pip against this path.\n"
    "  - contains /uv/tools/ or `$PY -m pip --version` errors with 'No "
    "module named pip' → uv-tool-managed, likely has no pip at all. Fix is "
    "`uv tool uninstall micro-cc && uv tool install micro-cc`.\n"
    "  - contains /Cellar/ or /homebrew/ → Homebrew python, check for the "
    "PEP 668 marker: `$PY -c \"import sysconfig,os; "
    "print(os.path.exists(sysconfig.get_path('stdlib')+'/EXTERNALLY-"
    "MANAGED'))\"`. If True, this install only works at all because "
    "someone passed --break-system-packages once, and self-update's plain "
    "pip call will fail (or silently corrupt) the same way. Recommend "
    "reinstalling via pipx or a pyenv-built interpreter instead — do not "
    "recommend --break-system-packages again, that's a landmine for "
    "unrelated system packages.\n"
    "  - contains /.pyenv/versions/ or a plain venv path → healthy, this is "
    "the supported path, self-update should just work. Say so plainly if "
    "nothing else is wrong.\n"
    "Also worth a quick check regardless of the above: can $PY actually "
    "write to its own site-packages? "
    "`$PY -c \"import site,os; d=site.getsitepackages()[0]; "
    "print(os.access(d, os.W_OK))\"` — False means every update will fail "
    "with a permission error no matter which category above it falls "
    "into, and the fix is the same reinstall-via-pipx/pyenv advice.\n"
    "CRITICAL: never run `pip uninstall micro-cc`, `pipx uninstall "
    "micro-cc`, `uv tool uninstall micro-cc`, or any reinstall of micro-cc "
    "yourself via bash_ in this session — you would be deleting the "
    "package whose code is the process currently running you, mid-run. "
    "Instead print the exact command(s) for the diagnosed fix, tell the "
    "user to open a NEW terminal window, run them there, then start "
    "`microcc` fresh in that new terminal once done. Report what you found "
    "plainly before giving the fix — don't just dump commands with no "
    "explanation of what was actually wrong.\n"
)

MESSAGE_SESSION = (
    "The user ran /message-session to learn about (or use) the "
    "message_session_ tool — it sends a message to another micro-cc "
    "session, identified purely by the project_dir it was launched "
    "against (a live TUI in another terminal, or a headless/batch run — "
    "past, present, or future). It's a discoverable tool, not always in "
    "context — call it directly by name (message_session_(action=\"list\") to find "
    "live sessions, message_session_(action=\"send\", target_project_dir, "
    "message) to message one) and it loads itself, no need to search_tools "
    "for it first.\n"
    "Delivery has two paths, tried in order: (1) live — if a TUI is open "
    "right now on target_project_dir, it lands as an incoming turn there "
    "immediately if that session is idle, or queued to run right after "
    "its current turn if it's busy (including if it's mid-/gui — same "
    "queue, same eventual delivery, just deferred until it's free). "
    "(2) durable fallback — if nothing is live there, the message is "
    "written into that project's inbox instead and picked up "
    "automatically the next time anyone runs headless/TUI against that "
    "project_dir, even if that's well after this call returns. Either "
    "way the call returns immediately — it never blocks waiting for the "
    "other side to actually read it. Mechanism: "
    f"{_PKG_DIR}/tools/message_session_.py, backed by "
    f"{_PKG_DIR}/utils/session_ipc_.py (the live "
    "socket path) and "
    f"{_PKG_DIR}/utils/inbox_store_.py (the durable fallback path, "
    "fcntl-locked since its writers are separate OS processes).\n"
    "Typical uses: coordinating with a sibling subagent you spawned via "
    "/graph (tell one to message_session_ its findings to another when "
    "done), or nudging a live session running in another terminal. If "
    "the user describes an actual message they want sent and to which "
    "project_dir, just call the tool yourself and report what happened — "
    "no need to interview them further than that.\n"
)

GRAPH = (
    "The user ran /graph to orchestrate multiple headless subagents "
    "(microcc-headless) toward a larger goal. There is no "
    "manifest file or JSON graph format here — you design the orchestration "
    "yourself, in your own reasoning, and adjust it as results come in. "
    "Don't build scaffolding for this; just do it. This project's own "
    "source is on disk — if you need the exact behavior behind any "
    "mechanism below instead of this paraphrase (debugging something "
    "unexpected, or just want ground truth), read_ the file named next "
    "to it. This whole mechanism explanation is also saved as the "
    "graph-orchestration skill — this turn's version of it can scroll out "
    "of context or get compressed away later, so call "
    "read_skill('graph-orchestration') any time afterward (a checkpoint "
    "wakeup is the obvious moment) to reload it in full:\n"
    "1. Before spawning anything, draw a plain ASCII diagram of the "
    "orchestration you're proposing (which subagents, what each one does, "
    "sequence/dependencies between them, and who's parallel vs. blocking) "
    "and show it to the user. Get their sense of it before firing anything "
    "off — cheap to redraw, expensive to redo once several subagents are "
    "already running against the wrong plan. Then write_ that plan to "
    "GRAPH_PLAN.md in this project directory — the diagram alone in the "
    "conversation isn't enough, because a checkpoint wakeup (step 4) may "
    "be the only context you have left by the time a subagent finishes: "
    "this turn's instructions can scroll out of a long conversation or get "
    "compressed away by auto-summarization, but a file you can read_ back "
    "always survives that. Include in it: (a) a one-line reminder of the "
    "mechanism itself (you're using bash_ + microcc-headless to spawn, "
    "monitor_ (action='check') to check status, message_session_ for subagents to "
    "coordinate directly, and get woken automatically on a checkpoint) so "
    "the file bootstraps a from-scratch understanding even with zero "
    "memory of this conversation, and (b) the actual plan — each "
    "subagent's project_dir and job, dependencies, current stage. Update "
    "this file as the plan evolves (step 4) — it's the durable source of "
    "truth, the diagram you showed the user was just the pitch.\n"
    "2. Spawn each subagent with bash_: `microcc-headless <project_dir> "
    "\"<prompt>\"` — NO trailing `&`. Spawned from your bash_, it registers "
    "the subagent, detaches it into the background itself, and returns "
    "within a second or two with either `▶ STARTED — <name> running detached "
    "as pid N (log: ...)` or `✗ REFUSED — <why>`. REFUSED means it did not "
    "start: most often the concurrent-subagent cap (the user's /subagents "
    "setting, default 4) is reached — wait for a checkpoint wakeup (or stop "
    "one) and spawn it again then; don't retry in a loop. microcc-headless runs project_dir's conversation through ONE "
    "autonomous turn with dangerous_tools=set() — no approval gate, so "
    "scope each subagent's prompt safely — and automatically appends a "
    "status-marker instruction to it (the model must end its reply with "
    "STATUS: DONE/NEEDS_INPUT/FAILED); that's where the DONE/FAILED/"
    "PAUSED/NEEDS_INPUT checkpoints in steps 3-4 below come from, you "
    f"don't add that instruction yourself ({_PKG_DIR}/start_headless_.py "
    "has the exact mechanism). Give each subagent its own project_dir (a fresh path = a clean "
    "isolated conversation scope — decided by you turn-by-turn here, "
    "versus /batch's fixed list of named tasks predeclared upfront in one "
    "manifest file). You can pick a different --model per subagent if the "
    "task calls for it (e.g. a cheaper/faster model for a simple fan-out "
    f"step, a stronger one for the synthesis step) — valid aliases: {', '.join(MODEL_OPTIONS)}. "
    "Use one of these exactly — an unrecognized alias is passed straight "
    "through to the API unchanged (by design, so a typo fails loudly "
    "instead of silently downgrading to the default model) and the spawn "
    "will just error. You can also pass --max-loops <N> to a subagent whose "
    "task is open-ended enough to risk looping forever instead of "
    "converging — it self-stops with STATUS: PAUSED (same checkpoint as a "
    "real question_asked, relaunch the same project_dir to continue) once "
    "it hits N tool-call rounds; omit it for a naturally bounded task, "
    "unlimited is the default.\n"
    "3. The moment you run a bash_ command containing microcc-headless, "
    "that subagent is automatically tracked — no separate registration "
    "step, no need to call anything just to \"start watching\" it. You'll "
    "see an ambient status line appear under the input showing all tracked "
    "subagents, and you'll automatically get woken up with a new turn the "
    "instant one of them hits a checkpoint (DONE, FAILED, PAUSED, or "
    "NEEDS_INPUT) — so you genuinely don't need to sit and poll. You can "
    "still call monitor_(action='check', targets=[project_dirs...]) any time "
    "you want an on-demand snapshot instead of waiting to be woken (e.g. "
    "right after spawning a batch, or to check something not auto-tracked "
    "yet) — monitor_ is only in scope on a turn where there's actually a "
    "tracked subagent, a backgrounded bash process, or an active watch to "
    "check on, so you won't see it otherwise. For something you'd "
    "otherwise have to poll for repeatedly (watching a subagent's own log/ "
    "output file, or any bash_-backgrounded process, for a specific "
    "condition), prefer monitor_(action='watch', command=..., "
    "description=...) instead — a shell filter over the thing you're "
    "watching, pushed to you as its own turn the moment it matches, so you "
    "don't have to remember to check back in.\n"
    f"Tracking/wakeup mechanism lives in {_PKG_DIR}/utils/"
    f"subagent_tracker_.py (the tracked-list itself) and {_PKG_DIR}/"
    "start_live_.py's "
    "_poll_subagents_tick/_wake_for_subagent (the polling/waking loop); "
    "monitor_'s own status-reading and watch logic is in "
    f"{_PKG_DIR}/tools/monitor_.py and {_PKG_DIR}/tools/monitor_watch_.py.\n"
    "4. When woken (or when you check in), decide what to do with what "
    "changed — that's the \"dynamic reevaluation\" part, not a fixed "
    "pipeline: PAUSED means the subagent hit a question it couldn't answer "
    "itself and already exited — decide the answer yourself if you can, or "
    "ask the user, then relaunch it with `microcc-headless <same "
    "project_dir> \"<answer>\"` to continue its exact same history. FAILED "
    "means decide whether to retry, redesign that branch, or abandon it. "
    "DONE means decide what depends on it and whether to kick that off now. "
    "Whatever you decide, update GRAPH_PLAN.md to reflect it — a stale plan "
    "file is worse than no plan file, since a future wakeup (or a future "
    "you, with no memory of this turn) will trust what it says.\n"
    "5. Subagents can coordinate directly with each other via "
    "message_session_(action=\"send\", target_project_dir, message) from inside their own "
    "prompts — e.g. tell one \"when you're done, message_session_ your "
    "findings to <sibling's project_dir>\". This works even if the sibling "
    "isn't running right now (durable inbox fallback — picked up next time "
    "that project_dir runs), so you don't have to be the relay for "
    "everything. Mechanism: "
    f"{_PKG_DIR}/tools/message_session_.py, "
    f"backed by {_PKG_DIR}/utils/session_ipc_.py (live socket path) and "
    f"{_PKG_DIR}/utils/inbox_store_.py (durable fallback path).\n"
    "6. To stop a running subagent (e.g. to kill and relaunch one that "
    "looks stuck): kill its OS pid. The pid is in the STARTED line its "
    "spawn returned, and monitor_(action='check') shows it too, together "
    "with an activity line (\"running bash_ for 3m\" vs \"waiting on the "
    "model for 4m\") — use that to tell stuck from slow before killing. "
    "A plain `kill <pid>` (SIGTERM) stops it gracefully: its in-flight and "
    "backgrounded shell commands are killed with it and its transcript ends "
    "cleanly with STATUS: FAILED — stopped by SIGTERM, so relaunching the "
    "same project_dir continues without a corrupt turn. "
    "If the pid has scrolled out of context, fall back to the tracker entry's "
    "own \"pid\" field (deterministic path in point 7 below), set from the "
    "subagent's own os.getpid() at self-registration — not inferred, not "
    "pattern-matched. Do NOT use `ps`/`pgrep` pattern-matching on command "
    f"text (e.g. `pgrep -f \"microcc-headless.*<project_dir>\"`): {_PKG_DIR}"
    "/start_headless_.py's own docstring documents that this exact style "
    "of approach — regex/shlex over `ps aux | grep microcc-headless`-ish "
    "output — was tried before, for the tracker's own registration, and "
    "abandoned because it can't reliably tell a real microcc-headless "
    "invocation apart from the literal string microcc-headless appearing "
    "anywhere, and mistracked garbage project_dirs in production. Once you "
    "have the pid: bash_(\"kill <pid>\"). That is the ENTIRE stop "
    "mechanism — do not also try to edit, delete, or \"clean up\" the "
    "tracker file yourself afterward, and do not grep/find anywhere just "
    "to locate or verify the tracker; that's the mistake that reliably "
    "times out a turn. "
    f"{_PKG_DIR}/start_live_.py's _poll_subagents_tick already self-heals "
    "this on its own next 3s tick: it notices os.kill(pid, 0) now raises "
    "ProcessLookupError, marks that entry FAILED itself with summary "
    "\"process is no longer running (stopped or killed before "
    "finishing)\", and fires the same checkpoint wakeup you'd get from a "
    "natural completion — the subagent disappears from the status line "
    "and you get notified on your own, zero extra action needed once the "
    "pid is dead.\n"
    "7. Never use `find /` or any other unscoped whole-filesystem search to "
    "locate a mechanism's source file or a tracker/state file — it walks "
    "every mounted volume, iCloud-synced folder, node_modules tree, and "
    "system directory, and reliably blows past a bash_ call's timeout "
    "before finding anything. Every mechanism above already names its own "
    "path (relative to this package's own directory) — read_/grep_ that "
    "path directly. If you genuinely need to search, scope it to this "
    "package's directory or ~/.micro-cc/, never `/`. The tracker file in "
    "particular never needs finding at all: its path is fully "
    "deterministic from the boss's own project_dir. utils/helpers.py's "
    "project_hash() does sha256(abspath(project_dir).encode())."
    "hexdigest()[:16], and utils/msg_store_.py's _get_storage_dir() "
    "combines that with the project_dir's basename (non [A-Za-z0-9_-] "
    "chars replaced with \"_\") to get "
    "~/.micro-cc/projects/{safe_basename}_{hash}/tracked_subagents.json — "
    "compute it, or `ls ~/.micro-cc/projects/` and match the readable "
    "prefix, instead of grepping/finding for it.\n"
    "Ask the user what they actually want accomplished before designing "
    "anything, if it isn't already clear from the conversation.\n"
)

OPTIMIZE = (
    "The user ran /optimize to start (or check on) an autonomous "
    "measure -> change -> keep-or-revert loop against a metric — benchmark "
    "time, test pass rate, cost, output quality, anything a shell command "
    "can print a number for. This is entirely file-based state under "
    "`.auto/` in the project directory (prompt.md, measure.sh, log.jsonl, "
    "optional checks.sh) — no registered tool exists for this, you drive "
    "it yourself with bash_/read_/write_/edit_, round after round, without "
    "asking permission each time. The full mechanism (file formats, setup "
    "steps, per-round procedure, guardrails) is saved as the autoresearch "
    "skill — this turn's version of it can scroll out of context or get "
    "compressed away later, so call read_skill('autoresearch') now if you "
    "haven't already this session, and again any time you need the exact "
    "procedure back (a checkpoint/resume is the obvious moment).\n"
    "If `.auto/` doesn't exist yet in this project: this is first-time "
    "setup — the skill's Setup section covers writing prompt.md and "
    "measure.sh together with the user and taking the baseline "
    "measurement before changing anything.\n"
    "If `.auto/` already exists: tail .auto/log.jsonl to see what's been "
    "tried and what the current best is, then resume the loop from there "
    "unless the user's /optimize argument says otherwise.\n"
    f"{_PKG_DIR}/start_live_.py's bottom status bar shows a live one-line "
    "summary of .auto/log.jsonl (round count, current best, last decision) "
    "for as long as this loop is active in a TUI session — you don't need "
    "to announce progress in chat every round, the user can see it "
    "there.\n"
    "Ask what the goal and metric actually are before writing anything, "
    "if it isn't already clear from the conversation or from an existing "
    "`.auto/prompt.md`.\n"
)

PROMPT_BODIES = {
    "/setup": SETUP,
    "/new-skill": SKILL,
    "/new-mcp": MCP,
    "/headless": HEADLESS,
    "/graph": GRAPH,
    "/message-session": MESSAGE_SESSION,
    "/skills": SKILLS_INFO,
    "/mcp": MCP_INFO,
    "/doctor": DOCTOR,
    "/optimize": OPTIMIZE,
}


def build(name: str, extra: str = "") -> str:
    """Wrap a prompt body into the hidden system-reminder turn."""
    return (
        "<system-reminder>\n"
        + PROMPT_BODIES[name]
        + (f"They also said: {extra}\n" if extra else "")
        + "</system-reminder>"
    )
