// Tool action labels, keyed by tool name.
// Consumed inline by TOOL_LABELS in components/tool-registry.ts via getCopy().
export const toolsCopy = {
  en: {
    tool_approval_ask: 'Run',
    tool_approval_hint: 'Enable tools in ⌘Preferences',
    todo_tool_: 'Scratchpad..',
    memory: 'Memory',
    search_tools: 'Finding the right tool',
    read_skill: 'Reading my skill',
    list_skills: 'Listing all my skills',
    kernel: 'Running Python code',
    launch_webapp: 'Launching web application',
    vision: 'Analyzing image',
    manifold: 'Searching Manifold insights',
    web_search: 'Searching the web',
    visit_url: 'Visiting website',
    download_from_url: 'Downloading from URL',
    page_up: 'Scrolling up',
    page_down: 'Scrolling down',
    find_on_page: 'Finding on page',
    find_next: 'Finding next occurrence',
    search_in_user_docs: 'Searching in documents',
    search_on_sharepoint_vector: 'Searching in SharePoint',
    find_in_MIDO_index: 'Searching MIDO index',
    search_vn_deviations: 'Searching on SharePoint (Odchylky)',
    find_in_katalog_chyb_: 'Searching in Katalog chyb',
    find_in_problem_records_: 'Searching in Problem records',
    fetch_sharepoint_document: 'Fetching SharePoint document',
    text_file: 'Working with text file',
    archive_search: 'Searching archive',
    legal_review: 'Reviewing legal document',
    translate_doc: 'Translating document',
    gen_report_for_admin: 'Generating report',
    outlook_mail: 'Outlook Mail',
    outlook_calendar: 'Outlook Calendar',
    teams: 'Teams',
    execute_mysql_query: 'Executing MySQL query',
    list_mysql_tables: 'Listing MySQL tables',
    describe_mysql_table: 'Describing MySQL table',
    tableau_list_datasources: 'Listing Tableau datasources',
    tableau_tool_get_fuzzy_metadata_vds: 'Getting Tableau metadata',
    tableau_tool_query_datasource_vds: 'Querying Tableau datasource',
    tableau_cached_report: 'Reviewing Tableau quick report',
    search_ct_gov_: 'Searching ClinicalTrials.gov',
    search_eu_ct_: 'Searching EU Clinical Trials',
    search_cteu_: 'Searching CTEU database',
    fetch_trials: 'Fetching clinical trials',
    fetch_batch_trials: 'Fetching batch of trials',
    fetch_ct_gov_daily_: 'Fetching daily CT.gov updates',
    search_regulatory_documents: 'Searching regulatory documents',
    list_regulatory_countries: 'Listing regulatory countries',
    list_docs_per_country: 'Listing documents by country',
    image_gen: 'Generating image',
  },
};
